accounts/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path(r'register/', views.RegisterView.as_view(success_url='/'), name='register'),
    path(r'login/', views.LoginView.as_view(success_url='/'), name='login'),
    path(r'logout/', views.LogoutView.as_view(), name='logout'),
    path(r'result/', views.account_result, name='result'),
]

dandelion/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls',namespace='account')),
    path('', include('portal.urls', namespace='portal')),
    path('', include('posts.urls', namespace='posts')),
    path('', include('comments.urls', namespace='comments')),
    # 收集后的静态文件
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}, name='static'),
    # 上传文件
    # re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),

]

posts/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path(r'article_index/', views.IndexView.as_view(), name='article_index'),
    # path(r'digital_file/', views.DigitalFileView.as_view(), name='digital_file'),
    path(r'digital_file/', views.get_digital_file, name='digital_file'),
    path(r'edit_article/', views.EditArticleView.as_view(), name='edit_article'),
    path(r'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html',
         views.ArticleDetailView.as_view(),name='get_detail_by_id')
]

posts/forms.py
from django import forms
from django.contrib.auth import get_user_model, password_validation
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.forms.forms import Form
from django.core.exceptions import ValidationError
from django.forms import widgets

from .models import DigitalFile
from accounts.models import NormalUser

class ArticleListForm(Form):
    pass


class DigitalFileForm(forms.ModelForm):
    name = forms.CharField(label='姓名', max_length=100, required= True)
    gender = forms.CharField(label='性别', max_length=100, required=True)
    birthday = forms.DateField(label='出生日期（年/月/日）')
    # 并不会显示
    day = widgets.DateInput(
        attrs={'label':'shengri','class':'form-control'}
    )

    # 此类为ModelForm
    class Meta:
        model = DigitalFile
        fields = '__all__'

posts/views.py
import logging
from django.contrib.auth import get_user_model, REDIRECT_FIELD_NAME
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from django.forms.forms import Form
from django.shortcuts import render, get_object_or_404
from django.conf import settings
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponseForbidden, HttpResponse
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView, RedirectView, ListView, DetailView, CreateView
from django.utils.decorators import method_decorator

from accounts.models import NormalUser
from .models import DigitalFile, LinkShowType, Article, Category, Tag
from .forms import ArticleListForm, DigitalFileForm
from comments.forms import CommentsForm
from dandelion.utils import send_email, get_sha256, get_current_site, generate_code, cache

# Create your views here.

logger = logging.getLogger(__name__)

class ArticleListView(ListView):
    '''
    文章列表
    '''
    # ListView: 一个表示对象列表的页面。当该视图执行时，self.object_list 将包含该视图正在操作的对象列表（通常，但不一定是查询集）。

    # form_class = ArticleListForm
    template_name = 'posts/article_index.html'
    # context_object_name属性用于给上下文变量取名（在模板中使用该名字），此处即list
    context_object_name = 'article_list'

    # 页面类型，分类目录或标签列表等
    page_type = ''
    paginate_by = settings.PAGINATE_BY
    page_kwarg = 'page'
    link_type = LinkShowType.L

    @property
    def page_number(self):
        page_kwarg = self.page_kwarg
        page = self.kwargs.get(page_kwarg) or self.request.GET.get(page_kwarg) or 1
        return page

    def get_queryset_cache_key(self):
        """
        子类重写.获得queryset的缓存key
        """
        raise NotImplementedError()

    def get_queryset_data(self):
        """
        子类重写.获取queryset的数据
        """
        raise NotImplementedError()


    def get_queryset_from_cache(self,cache_key):
        '''
                缓存页面数据
                :param cache_key: 缓存key
                :return:
                '''
        value = cache.get(cache_key)
        # 已经存入缓存中
        if value:
            logger.info('get view cache.key:{key}'.format(key=cache_key))
            return value
        # 还没存入缓存中
        else:
            article_list = self.get_queryset_data()

            # 缓存
            cache.set(cache_key, article_list)

            logger.info('set view cache.key:{key}'.format(key=cache_key))
            return article_list

    def get_queryset(self):
        '''
        从缓存中获取数据（ListView预置方法，此为重写）
        '''
        key = self.get_queryset_cache_key()
        value = self.get_queryset_from_cache(key)
        return value

    def get_context_data(self, **kwargs):
        kwargs['linktype'] = self.link_type
        return super().get_context_data(**kwargs)


class IndexView(ArticleListView):
    '''
    首页
    '''
    link_type = LinkShowType.I

    def get_queryset_data(self):
        # 已发表的文章
        article_list = Article.objects.filter(type='a', status='p')
        return article_list

    def get_queryset_cache_key(self):
        cache_key = f'index_{self.page_number}'
        return cache_key


class ArticleDetailView(DetailView):
    '''
    文章详情
    '''

    # DetailView: 当该视图执行时，self.object 将包含该视图正在操作的对象。
    template_name = 'posts/article_detail.html'
    model = Article
    pk_url_kwarg = 'article_id'
    context_object_name = 'article'

    def get_object(self, queryset=None):
        obj = super().get_object()
        obj.viewed()
        self.object = obj
        return obj

    # 返回用于显示对象的上下文数据
    def get_context_data(self, **kwargs):
        # articleid = int(self.kwargs[self.pk_url_kwarg])
        print('ArticleDetailView看看context data里都有啥：',self.object)
        comment_form = CommentsForm()
        user = self.request.user
        # 如果用户已经登录，则隐藏邮件和用户名输入框
        if user.is_authenticated :
            comment_form.fields.update({
                'email': forms.EmailField(widget=forms.HiddenInput()),
                'name': forms.CharField(widget=forms.HiddenInput()),
            })
            comment_form.fields["email"].initial = user.email
            comment_form.fields["name"].initial = user.username

        article_comments = self.object.comment_list()

        kwargs['form'] = comment_form
        kwargs['article_comments'] = article_comments
        kwargs['comment_count'] = len(
            article_comments) if article_comments else 0

        kwargs['next_article'] = self.object.next_article()
        kwargs['prev_article'] = self.object.prev_article()

        return super().get_context_data(**kwargs)


class EditArticleView(CreateView):
    '''
    编辑发帖
    '''

    # 直接用django内置form把article中的属性给布置好了
    model = Article
    template_name = 'posts/edit_article.html'
    fields = ['author',
              'title',
              'content',
              # 'tags',
              ]

    # 自动匹配author
    def form_invalid(self, form):
        print('EditArticleView看看：',form)
        user = self.request.user
        if user.is_authenticated:
            pass








# 数字化档案
def get_digital_file(request):
    try:
        # 如果是POST请求，则接收表单
        if request.method == 'POST':
            # form = DigitalFileForm(request.POST)
            resp = request.POST
            print('forms:', resp)
            digi_file = DigitalFile()
            inves_name = resp['investigator']
            digi_file.investigator = NormalUser.objects.get(username=inves_name)
            digi_file.inves_time = resp['inves_time']

            # 基本信息
            digi_file.name = resp['name']
            if '男' in resp['gender']:
                digi_file.gender = 1
            elif '女' in resp['gender']:
                digi_file.gender = 0
            digi_file.birthday = resp['birthday']
            digi_file.school = resp['school']
            digi_file.grade_and_class = resp['grade_and_class']
            digi_file.school_address = resp['school_address']
            digi_file.height = resp['height']
            digi_file.weight = resp['weight']
            digi_file.shoe_size = resp['shoe_size']
            digi_file.hobbies = resp['hobbies']
            digi_file.academic_record = resp['academic_record']
            digi_file.contact_of_teacher = resp['contact_of_teacher']
            digi_file.contact_of_parent = resp['contact_of_parent']
            digi_file.home_address = resp['home_address']
            digi_file.home_postal_code = resp['home_postal_code']
            digi_file.single_parent_or_not = resp['single_parent_or_not']
            digi_file.low_income_or_not = resp['low_income_or_not']
            digi_file.orphan_or_not = resp['orphan_or_not']
            digi_file.your_little_wish = resp['your_little_wish']
            digi_file.the_most_eager_thing_to_do = resp['the_most_eager_thing_to_do']

            # 家庭情况
            # （一对多关系：一个调查对象对多位家庭成员）


            # 家庭经济收入情况
            digi_file.debt_situation = resp['debt_situation']
            digi_file.biggest_difficulty_of_family = resp['biggest_difficulty_of_family']
            digi_file.family_assets = resp['family_assets']
            digi_file.housing_situation = resp['housing_situation']
            digi_file.main_source_of_monthly_income = resp['main_source_of_monthly_income']

            # 受资助情况
            if resp['live_in_school_or_not']:
                digi_file.live_in_school_or_not = True
            else:
                digi_file.live_in_school_or_not = False
            digi_file.expenses_of_living_in_school = resp['expenses_of_living_in_school']
            if resp['paid_or_not']:
                digi_file.paid_or_not = True
            else:
                digi_file.paid_or_not = False
            digi_file.other_help_received = resp['other_help_received']
            digi_file.reward_received = resp['reward_received']

            # 学生自述
            digi_file.statement_of_student = resp['statement_of_student']

            # 班主任评语
            digi_file.comments_of_teacher = resp['comments_of_teacher']

            # 家访手记及意见
            digi_file.home_visit_notes_and_opinions = resp['home_visit_notes_and_opinions']

            # 评定贫困程度
            if resp['orphan']:
                digi_file.orphan = True
            else:
                digi_file.orphan = False
            if resp['single_parent']:
                digi_file.single_parent = True
            else:
                digi_file.single_parent = False
            if resp['illness_or_paralysis']:
                digi_file.illness_or_paralysis = True
            else:
                digi_file.illness_or_paralysis = False
            if resp['multi_children']:
                digi_file.multi_children = True
            else:
                digi_file.multi_children = False
            if resp['lack_of_workforce']:
                digi_file.lack_of_workforce = True
            else:
                digi_file.lack_of_workforce = False
            digi_file.other_types = resp['other_types']
            digi_file.remarks = resp['remarks']

            digi_file.save()

            title = "提交成功！"
            content = "家访调查表已成功提交！感谢您为孩子们的付出！"
            return render(request, 'posts/thanks.html', {'title': title, 'content': content})

        # 如果是GET请求，则返回空表单让用户填写
        else:
            form = DigitalFileForm()
        # 没填写完则继续填写
        return render(request, 'posts/digital_file.html', {'form': form})
    except Exception as e:
        return HttpResponse('哎呀，发生错误了...', repr(e))


# 数字化档案
class DigitalFileView(FormView):
    # 要有form_class才能做后面的事
    form_class = DigitalFileForm
    template_name = 'posts/digital_file.html'
    redirect_field_name = REDIRECT_FIELD_NAME

    def form_valid(self, form):
        print(111)
        # form = Form(data=self.request.POST)
        if form.is_valid():
            print('form: ', form)

templates/posts/article_detail.html
{% extends 'common/base.html' %}
{% load posts_tags %}
{% block header %}
    <link rel="stylesheet" href="{% static 'posts/css/base_posts.css'%}">
    <script src="{% static 'posts/js/posts.js' %}"></script>
    <title>文章详情</title>
{% endblock %}
{% block content %}
    <div id="primary" class="site-content">
        <div id="content" role="main">
            {#        文章详情#}
            {% load_article_detail article False user %}
        <br><hr><br>

            {#文章导航#}
            {% if article.type == 'a' %}
                <nav class="nav-single">
                    <h3 class="assistive-text">文章导航</h3>
                    {% if next_article %}
                        <span class="nav-previous"><a href="{{ next_article.get_absolute_url }}" rel="prev"><span
                                class="meta-nav">&larr;</span> {{ next_article.title }}</a></span>
                    {% endif %}
                    {% if prev_article %}
                        <span class="nav-next"><a href="{{ prev_article.get_absolute_url }}"
                                                  rel="next">{{ prev_article.title }} <span
                                class="meta-nav">&rarr;</span></a></span>
                    {% endif %}
                </nav><!-- .nav-single -->
            {% endif %}

        </div><!-- #content -->
        <br><hr><br>

        {#            评论区#}
        {#        {% if article.comment_status == "o" and OPEN_SITE_COMMENT %}#}
        {% include 'comments/tags/comment_list.html' %}
        {% if user.is_authenticated %}
            {% include 'comments/tags/post_comment.html' %}
        {% else %}
            <div class="comments-area">
                <h2 class="comment-meta text-center">您还没有登录，请您<a
                        href="{% url "account:login" %}?next={{ request.get_full_path }}" rel="nofollow">登录</a>后发表评论。
                </h2>

                {#                    {% load oauth_tags %}#}
                {#                    {% load_oauth_applications request %}#}

            </div>
        {% endif %}
    <br><br>
        {#        {% endif %}#}
    </div><!-- #primary -->
{% endblock %}

templates/posts/article_index.html
{% extends 'common/base.html' %}
{% load static %}
{% load posts_tags %}
{% load cache %}
{% block header %}
    <link rel="stylesheet" href="{% static 'posts/css/base_posts.css' %}">
    <title>论坛首页</title>
{% endblock %}

{% block content %}
    <div id="main">
    <br>
    <div id="subs"  class="text-center" style="display: flex;justify-content: center;align-items: center">
        <a href="{% url 'posts:digital_file' %}">
            <button class="btn btn-lg btn-primary btn-block text-center" id="submit_btn">电子档案</button>
        </a>
        <span style="width:3%"></span>
        <a href="{% url 'posts:edit_article' %}">
            <button class="btn btn-lg btn-primary btn-block text-center" id="submit_btn">创建帖子</button>
        </a>

    </div>
    <br>
        <div id="contents">
        {% if user.is_authenticated %}
        {#  需要一个循环，把数据库里的article都读出来  #}
            {% for article in article_list %}
                <p>
                {% load_article_detail article True user %}
                </p><hr>
            {% empty %}
                <div class="jumbotron">
                    <h1 class="display-4 text-center">这里还没有帖子<br><br>😀😀😀</h1>
                    <br><br>
                    <p class="lead">请点击右上角的发帖按钮发表第一篇帖子吧！</p>
                </div>
            {% endfor %}
{#            分页#}
{#             {% if is_paginated %}#}
{#                {% load_pagination_info page_obj page_type tag_name %}#}
{#            {% endif %}#}
        {% else %}
             <h2 class="text-center"> 您还没有<a href="{% url 'account:login' %}">登录</a>，无法访问此页面！ </h2>
        {% endif %}
        </div>
    </div>
{% endblock %}

templates/posts/edit_article.html
{% extends 'common/base.html' %}
{% block header %}
    <link rel="stylesheet" href="{% static 'posts/css/base_posts.css' %}">
    <title>创建帖子</title>
{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <header class="text-center">
            <h2>创建你的帖子</h2>
            <p>（请友善发言噢~）</p>
        </header>
        <br><br>
        <form class="text-center" action="{% url 'posts:edit_article' %}" method="post">
        {% csrf_token %}
{#            django内置表单，Article类形成的form#}


        {{ form.as_p }}
{#            <div id="title-of-article" style="font-size: 24px;">#}
{#                {{ form.title.label_tag }}#}
{#                {{ form.title }}#}
{#                {{ form.title.errors }}#}
{#            </div>#}
{#            <br><br>#}
{#             <div id="content-of-article">#}
{#                {{ form.content.label_tag }}#}
{#                {{ form.content }}#}
{#                {{ form.content.errors }}#}
{#            </div>#}



            <br>
        <button class="btn btn-lg btn-primary btn-block center-block text-center" type="submit" id="submit_btn">发帖</button>
        </form>
    {% else %}
            <h2 class="text-center"> 您还没有<a href="{% url 'account:login' %}">登录</a>，无法访问此页面！ </h2>
    {% endif %}
    <br><br>
{% endblock %}

templates/posts/error_page.html
{% extends 'common/base.html' %}
{% load posts_tags %}
{% load cache %}
{% block header %}
    {% if tag_name %}
        {% if statuscode == '404' %}
            <title>404 NotFound</title>
        {% elif statuscode == '403' %}
            <title>Permission Denied</title>
        {% elif statuscode == '500' %}
            <title>500 Error</title>
        {% else %}
            <title></title>
        {% endif %}
        {% comment %}<meta name="description" content="{{ page_type }}:{{ tag_name }}"/>{% endcomment %}
    {% else %}
        <title>{{ SITE_NAME }} | {{ SITE_DESCRIPTION }}</title>
    {% endif %}
    <meta name="description" content="{{ SITE_SEO_DESCRIPTION }}"/>
    <meta name="keywords" content="{{ SITE_KEYWORDS }}"/>
    <meta property="og:type" content="blog"/>
    <meta property="og:title" content="{{ SITE_NAME }}"/>
    <meta property="og:description" content="{{ SITE_DESCRIPTION }}"/>
    <meta property="og:url" content="{{ SITE_BASE_URL }}"/>
    <meta property="og:site_name" content="{{ SITE_NAME }}"/>
{% endblock %}
{% block content %}
    <div id="primary" class="site-content">
        <div id="content" role="main">

            <header class="archive-header">
                <h1 class="archive-title">{{ message }}</h1>
            </header><!-- .archive-header -->

        </div><!-- #content -->
    </div><!-- #primary -->

{% endblock %}


{% block sidebar %}
    {% load_sidebar user 'i' %}
{% endblock %}

templates/posts/thanks.html
{% extends 'common/base.html' %}

{% block header %}
    <title> {{ title }}</title>
{% endblock %}
{% block content %}
    <div id="primary" class="site-content">
        <div id="content" role="main">

            <header class="archive-header">

                <h2 class="archive-title text-center"> {{ content }}</h2>
            </header><!-- .archive-header -->
            <br/>
            <p class="text-center" id="turn-to-other-pages">
                <a href="/">回到首页</a>

            </p><!-- .archive-header -->
        </div>
    </div>
{% endblock %}