comments/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'comments'

urlpatterns = [
    path(r'article/<int:article_id>/post_comment', views.CommentsView.as_view(),name='post_comment')
]

dandelion/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls',namespace='account')),
    path('', include('portal.urls', namespace='portal')),
    path('', include('posts.urls', namespace='posts')),
    path('', include('comments.urls', namespace='comments')),
    # 收集后的静态文件
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}, name='static'),
    # 上传文件
    # re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),

]

posts/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path(r'article_index/', views.IndexView.as_view(), name='article_index'),
    # path(r'digital_file/', views.DigitalFileView.as_view(), name='digital_file'),
    path(r'digital_file/', views.get_digital_file, name='digital_file'),
    path(r'edit_article/', views.EditArticleView.as_view(), name='edit_article'),
    path(r'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html',
         views.ArticleDetailView.as_view(),name='get_detail_by_id')
]

comments/models.py
from django.conf import settings
from django.db import models
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from mdeditor.fields import MDTextField  # markdown
from uuslug import slugify  # slug

from posts.models import Article


# Create your models here.


class Comments(models.Model):
    id = models.AutoField(primary_key=True)
    post_time = models.DateTimeField('评论时间', default=now)
    last_mod_time = models.DateTimeField('修改时间', default=now)
    # 支持markdown
    comment_body = models.TextField('评论正文', max_length=300)
    # 评论者
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name='评论者',
        blank=False,
        null=False,
    )
    # 评论哪篇文章
    article = models.ForeignKey(
        Article,
        on_delete=models.CASCADE,
        verbose_name='评论文章'
    )
    # 上级评论（comment_item_tree用），自关联
    parent_comment = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        verbose_name='上级评论',
        null=True,
    )
    is_enable = models.BooleanField(
        '是否显示', default=True, null=False)

    class Meta:
        ordering = ['-post_time']
        verbose_name = '评论'
        verbose_name_plural = verbose_name
        get_latest_by = 'id'

    def __str__(self):
        return str(self.author) + '评论： ' + self.comment_body

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

comments/forms.py
from django import forms
from django.contrib.auth import get_user_model, password_validation
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.forms.forms import Form
from django.core.exceptions import ValidationError
from django.forms import widgets

from .models import Comments
from accounts.models import NormalUser


class CommentsForm(forms.ModelForm):
    # url = forms.URLField(label='网址',required=False)
    email = forms.EmailField(label='电子邮箱',required=True)
    name = forms.CharField(label='姓名',required=True)
    parent_comment_id = forms.IntegerField(
        widget=forms.HiddenInput, required=False)

    class Meta:
        model = Comments
        fields = ['comment_body']

comments/views.py
import logging
from django import forms
from django.http import HttpResponseRedirect, HttpResponseForbidden, HttpResponse
from django.views.generic import FormView, RedirectView, ListView, DetailView, CreateView

from accounts.models import NormalUser
from posts.models import Article
from .models import Comments
from .forms import CommentsForm

import markdown
import emoji

# Create your views here.

logger = logging.getLogger(__name__)


class CommentsView(FormView):
    form_class = CommentsForm
    # 评论区渲染的页面应该是文章详情页
    template_name = 'posts/article_detail.html'

    # 定位到当前评论区的位置
    def get(self, request, *args, **kwargs):
        article_id = self.kwargs['article_id']
        article = Article.objects.get(pk=article_id)
        # 获取当前文章url（具体打开的是哪一篇文章）
        url = article.get_absolute_url()
        return self.render_to_response(self.get_form())

    # 表单数据不合法
    def form_invalid(self, form):
        article_id = self.kwargs['article_id']
        article = Article.objects.get(pk=article_id)
        print('不合法form',form.cleaned_data)

        if self.request.user.is_authenticated:
            # 改成HiddenInput
            form.fields.update({
                'email': forms.EmailField(widget=forms.HiddenInput),
                'name': forms.CharField(widget=forms.HiddenInput),
            })
            user = self.request.user
            form.fields['email'].initial = user.email
            form.fields['name'].initial = user.username

        return self.render_to_response({
            'form': form,
            'article': article
        })

    # 表单数据合法
    def form_valid(self, form):
        article_id = self.kwargs['article_id']
        article = Article.objects.get(pk=article_id)
        user = self.request.user
        print('合法form',form.cleaned_data)

        if not self.request.user.is_authenticated:
            email = form.cleaned_data['email']
            name = form.cleaned_data['name']
            user = NormalUser.objects.get_or_create(
                username=name, email=email
            )[0]

        comment = form.save(False)
        comment.article = article
        comment.author = user
        if form.cleaned_data['parent_comment_id']:
            parent_comment = Comments.objects.get(
                pk=form.cleaned_data['parent_comment_id']
            )
            comment.parent_comment = parent_comment
        # else:
        #     parents_comments = Comments.objects.get(pk=1)
        #     comment.parents_comments = parents_comments

        print(comment)
        comment.save(True)

        return HttpResponseRedirect(
            f'{article.get_absolute_url()}#div-comment-{comment.pk}'
        )

templates/comments/tags/comment_item_tree.html
{% load posts_tags %}
<li id="this-is-a-comment-tree-{{ comment.pk }}" class="depth-{{ depth }}">
    <div class="comment" id="this-is-a-comment-{{ comment.pk }}"
        style="display: flex;line-height: 2;font-size: 16px;">
        <div id="comment-avatar" class="" style="float: left">
            <p class="img-circle img-rounded"><img src=""></p>
        </div>
        <div id="comment-content" class="" style="float: right">
            <div class="" id="comment-info" style="color: grey">
                <a href="#comment-{{ comment.parent_comment.pk }}" style="">{{ comment.author.username }}</a>&nbsp;
                {{ comment.post_time }}
{#                {{ comment.post_time.year }}年{{ comment.post_time.month }}月{{ comment.post_time.day }}日&nbsp;#}
{#                {{ comment.post_time.hour }}:{{  comment.post_time.minute }}#}
            </div>

            {% if comment.parent_comment %}
                 <div>回复 <a
                        href="#comment-{{ comment.parent_comment.pk }}">@{{ comment.parent_comment.author.username }}</a>
                </div>
            {% endif %}
            <div class="" id="comment-body">
                {{ comment.comment_body }}
            </div>

{#        执行回复操作的js函数#}
        <div id="reply"style="font-size: 12px;">
            <button class=""
            onclick="do_reply {{ comment.pk }}">
                回复
            </button>
        </div>
        </div>
    </div>
</li><!-- #comment-## -->
{# 查询子评论 #}
{% query article_comments parent_comment=comment as cc_comments %}
{% for cc in cc_comments %}
    {% with comment_item=cc template_name="comments/tags/comment_item_tree.html" %}
        {% if depth >= 1 %}
            {% include template_name %}
        {% else %}
            {% with depth=depth|add:1 %}
                {% include template_name %}
            {% endwith %}
        {% endif %}
    {% endwith %}
{% endfor %}
<br>

templates/comments/tags/comment_list.html
{% load comments_tags %}
{% load posts_tags %}
{% load cache %}
<div id="comment-list">
<ul class="comment-tabs group">
    <h3 class="active" style="text-decoration: none;color: #348F50;"><a href="#comment-list"><i
                class="fa fa-comments-o" ></i>评论区&nbsp;<span>{% count_pc_number article %}</span></a></h3>
</ul>
    {% if article_comments %}
{#        {% cache 36000 article_comments article.id %}#}
        <div id="comment-list" class="comment-tab" style="display: block;">
            <ol class="comment">
            {#        查询该文章的所有根评论#}
                {% query article_comments parent_comment=None as primary_comments %}
                {% for comment in primary_comments %}
{#                    {{ comment.comment_body }}#}
                    {% with 0 as depth %}
                        {% include 'comments/tags/comment_item_tree.html' %}
                    {% endwith %}
                {% empty %}
                    <h3 class="display-4 text-center">此处还没有评论~</h3>
                {% endfor %}
            </ol><!--/.commentlist-->
        </div>
{#        {% endcache %}#}
    {% endif %}
</div>

templates/comments/tags/post_comment.html
<div id="post_comment" style="background: #f5f5f5;padding:3% 5%">
    <header>
        <h4 class="text-left">发表评论</h4>
    </header>
    <div id="comment-content" class="border-0" >
        <p>正文：</p>
        <form action="{% url 'comments:post_comment' article.pk %}" method="post">
            {% csrf_token %}
            <div class="comment" id="comment-form-comment">
                {#                {{ form.comment_body.label_tag }}#}
                <span style="height: 90px;width: 160px;">
                    {{ form.comment_body }}
                </span>

                {{ form.comment_body.errors }}
            </div>
            <div class="comment" id="comment-form-author">
                {% if not form.name.is_hidden %}
                    {{ form.name.label_tag }}

                {% endif %}
                {{ form.name }}
                {{ form.name.errors }}

            </div>
            <div class="comment" id="comment-form-email">
                {% if not form.email.is_hidden %}
                    {{ form.email.label_tag }}

                {% endif %}
                {{ form.email }}
                {{ form.email.errors }}
            </div>
            {{ form.parent_comment_id }}
            <br>
            <button type="submit" id="submit_btn" class="btn btn-lg btn-primary btn-block">发表评论</button>
        </form>
    </div><!-- #respond -->
</div><!-- #comments .comments-area -->