accounts/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path(r'register/', views.RegisterView.as_view(success_url='/'), name='register'),
    path(r'login/', views.LoginView.as_view(success_url='/'), name='login'),
    path(r'logout/', views.LogoutView.as_view(), name='logout'),
    path(r'result/', views.account_result, name='result'),
]

dandelion/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls',namespace='account')),
    path('', include('portal.urls', namespace='portal')),
    path('', include('posts.urls', namespace='posts')),
    path('', include('comments.urls', namespace='comments')),
    # 收集后的静态文件
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}, name='static'),
    # 上传文件
    # re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),

]

posts/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path(r'article_index/', views.IndexView.as_view(), name='article_index'),
    # path(r'digital_file/', views.DigitalFileView.as_view(), name='digital_file'),
    path(r'digital_file/', views.get_digital_file, name='digital_file'),
    path(r'edit_article/', views.EditArticleView.as_view(), name='edit_article'),
    path(r'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html',
         views.ArticleDetailView.as_view(),name='get_detail_by_id')
]

templates/common/base.html
<!-- base of templates-->
{% load static %}
{% load cache %}

<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->

    {% block header %}
    {% endblock %}

    <link href="{% static 'portal/css/home.css' %}" rel="stylesheet">

    <!--Font Awesome-->
    <link rel="stylesheet" href="https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
          integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"
            integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ"
            crossorigin="anonymous"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
            integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd"
            crossorigin="anonymous"></script>

    <!-- Bootstrap-table -->
    <link href="https://cdn.bootcdn.net/ajax/libs/bootstrap-table/1.19.1/themes/bootstrap-table/bootstrap-table.css" rel="stylesheet">
    <script src="https://cdn.bootcdn.net/ajax/libs/bootstrap-table/1.19.1/bootstrap-table-locale-all.js"></script>


    <!-- HTML5 shim 和 Respond.js 是为了让 IE8 支持 HTML5 元素和媒体查询（media queries）功能 -->
    <!-- 警告：通过 file:// 协议（就是直接将 html 页面拖拽到浏览器中）访问页面时 Respond.js 不起作用 -->
    <!--[if lt IE 9]>
    <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
    <![endif]-->
</head>
<body>

<div id="page" class="has-feedback">
    <header id="masthead" class="site-header" role="banner">
        <hgroup>
            <h1 class="site-title"><a href="/" title="{{ SITE_NAME }}" rel="home">{{ SITE_NAME }}</a>
            </h1>
            <h2 class="site-description">{{ SITE_DESCRIPTION }}</h2>
        </hgroup>

        {% include 'common/nav.html' %}

    </header><!-- #masthead -->

<div id="main" class="container">
    {% block content %}
    {% endblock %}

</div><!-- #main .wrapper -->

{% include 'common/footer.html' %}

</div><!-- #page -->
</body>
</html>

templates/common/base_account.html
{% load static %}

<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    {% block header %}{% endblock %}

    <link rel="stylesheet" href="{% static 'account/css/base_account.css' %}">

    <!--Font Awesome-->
    <link rel="stylesheet" href="https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
          integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <link href="../../statics/portal/css/home.css" rel="stylesheet">

    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"
            integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ"
            crossorigin="anonymous"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
            integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd"
            crossorigin="anonymous"></script>

    <!-- HTML5 shim 和 Respond.js 是为了让 IE8 支持 HTML5 元素和媒体查询（media queries）功能 -->
    <!-- 警告：通过 file:// 协议（就是直接将 html 页面拖拽到浏览器中）访问页面时 Respond.js 不起作用 -->
    <!--[if lt IE 9]>
    <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
    <![endif]-->
</head>

<body>
{% block content %}
{% endblock %}

<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->

</body>
    {# 暂时没用到 #}
    <script type="text/javascript" src="{% static 'blog/js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'account/js/account.js' %}" type="text/javascript"></script>
</html>

templates/common/footer.html
<!--底部-->
<footer>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-2 footer-1">
                <div>
                    <ul class="footer-menu">

                    </ul>
                </div>
            </div>
            <div class="col-lg-2 footer-2">
                <p></p>

            </div>
            <div class="col-lg-5 col-md-6 footer-3">
                <p></p>
            </div>
            <div class="col-lg-3 footer-4">
                <p></p>

            </div>

        </div>
    </div>
    <div class="row" class="center-block">
        <div class="col-md-8" class="text-center">
            版权所有 © 2021
            <a href="/" style="text-decoration: none;">蒲公英</a>
        </div>
        <div class="col-md-4 text-right">

        </div>
    </div>
</footer>

templates/common/nav.html
{% load static %}

<!--导航条-->
<nav class="navbar navbar-default navbar-expand-xl navbar-light navbar-fixed-top">
    <div class="container-fluid " style="">
        <!--logo-->
            <a id="menu-logo" class="navbar-brand col-md-1 col-lg-1" href="/"
               title="领航 · 蒲公英" itemprop="url">
                <img src="{% static 'portal/img/first/logo.png' %}"
                     style="height: 75px;width: 75px;">
                <span></span>
            </a>

        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <!--导航选项-->
        <div id="navbarDropdown " class="collapse navbar-collapse col-md-8 col-lg-8">
            <ul id="menu-items" class="nav navbar-nav ">
                <li id="menu-item-0 " class="">
                    <a id="menu-item-dropdown" title="论坛首页" href="{% url 'posts:article_index' %}">
                        <span class="nav-item">论坛首页</span>&nbsp;
                    </a>
                </li>
                <li id="menu-item-1 " class="">
                    <a id="menu-item-dropdown" class="dropdown-toggle" data-toggle="dropdown" title="我们的故事" href="#"
                       aria-haspopup="true" aria-expanded="false">
                        <span class="nav-item">我们的故事</span>&nbsp;
                        <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span>
                    </a>

                    <ul class="dropdown-menu" aria-labelledby="menu-item-dropdown-1" role="menu">
                        <li id="menu-item-1-1" class="dropdown-item">
                            <a title="团队介绍" href="" class="dropdown-item text-center">
                                <span class="dropdown-item">团队介绍</span>
                            </a>
                        </li>
                        <li id="menu-item-1-2" class="dropdown-item">
                            <a title="我们的荣誉" href="" class="dropdown-item text-center">
                                <span class="dropdown-item">我们的荣誉</span>
                            </a>
                        </li>
                        <li id="menu-item-1-3" class="dropdown-item">
                            <a title="创始⼈寄语" href="" class="dropdown-item text-center">
                                <span class="dropdown-item">创始⼈寄语</span>
                            </a>
                        </li>
                        <li id="menu-item-1-4" class="dropdown-item">
                            <a title="宣传⽚" href="" class="dropdown-item text-center">
                                <span class="dropdown-item">宣传⽚</span>
                            </a>
                        </li>
                        <li id="menu-item-1-5" class="dropdown-item">
                            <a title="logo含义" href="" class="dropdown-item text-center">
                                <span class="dropdown-item">logo含义</span>
                            </a>
                        </li>
                    </ul>
                </li>

                <li id="menu-item-2 " class="">
                    <a id="menu-item-dropdown" class="dropdown-toggle" data-toggle="dropdown" title="李莎精神" href="#"
                       aria-haspopup="true" aria-expanded="false">
                        <span class="nav-item">李莎精神</span>&nbsp;
                        <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span>
                    </a>

                    <ul class="dropdown-menu" aria-labelledby="menu-item-dropdown-2" role="menu">
                        <li id="menu-item-2-1" class="dropdown-item">
                            <a href="" class="dropdown-item text-center">
                                <span class="dropdown-item">标杆人物</span>
                            </a>
                        </li>
                        <li id="menu-item-2-2" class="dropdown-item">
                            <a href="" class="dropdown-item text-center">
                                <span class="dropdown-item">品牌历程</span>
                            </a>
                        </li>
                        <li id="menu-item-2-3" class="dropdown-item">
                            <a href="" class="dropdown-item text-center">
                                <span class="dropdown-item">李莎精神</span>
                            </a>
                        </li>
                        <li id="menu-item-2-4" class="dropdown-item">
                            <a href="" class="dropdown-item text-center">
                                <span class="dropdown-item">品牌愿景</span>
                            </a>
                        </li>
                        <li id="menu-item-2-5" class="dropdown-item">
                            <a href="" class="dropdown-item text-center">
                                <span class="dropdown-item">核心价值观</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li id="menu-item-3 " class="">
                    <a id="menu-item-dropdown" class="dropdown-toggle" data-toggle="dropdown" title="品牌服务" href="#"
                       aria-haspopup="true" aria-expanded="false">
                        <span class="nav-item">品牌服务</span>&nbsp;
                        <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span>
                    </a>

                    <ul class="dropdown-menu" aria-labelledby="menu-item-dropdown-3" role="menu">
                        <li id="menu-item-3-1" class="dropdown-item">
                            <a href="" class="dropdown-item text-center">
                                <span class="dropdown-item">服务模式</span>
                            </a>
                        </li>
                        <li id="menu-item-3-2" class="dropdown-item">
                            <a href="" class="dropdown-item text-center">
                                <span class="dropdown-item">公益支教</span>
                            </a>
                        <li id="menu-item-3-3" class="dropdown-item">
                            <a href="" class="dropdown-item text-center">
                                <span class="dropdown-item">公益评估</span>
                            </a>
                        </li>
                        <li id="menu-item-3-4" class="dropdown-item">
                            <a href="" class="dropdown-item text-center">
                                <span class="dropdown-item">活动回顾</span>
                            </a>
                        </li>
                    </ul>
                </li>

                <li id="menu-item-5 " class="">
                    <!--注册或登录-->
                    <span id="register-or-login" class="dropdown-toggle">
            <p class="text-center" style="padding-top: 40%;" id="login-or-not">
                {% if user.is_authenticated %}
                    <p>
                    您好，<a href="{% url 'posts:digital_file' %}">{{ user.username }}</a>！&nbsp;
                        <a href="{% url 'account:logout' %}">登出</a>
                    </p>
                {% else %}
                    <p>
                    <a href="{% url 'account:register' %}">注册</a>&nbsp;
                    或&nbsp;
                    <a href="{% url 'account:login' %}">登录</a>
                    </p>
                {% endif %}
                        </p>
        </span>
                </li>
            </ul>
        </div>
    </div>
</nav>